import "./globals.css";

// Metadata
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Homepage | LoremSwap",
	description: "Generated by create next app",
};

// Font
import { Poppins } from "next/font/google";

// Components
import Navbar from "@/components/navbar";
import BgEllipseSvgs from "@/components/BgEllipseSvgs";

// Providers
import RainBowKitCustomProvider from "@/providers/rainbowkitprovider";

const poppins = Poppins({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-poppins",
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${poppins.variable} bg-background text-light antialiased`}
			>
				<RainBowKitCustomProvider>
					<Navbar />
					{children}
					<BgEllipseSvgs />
				</RainBowKitCustomProvider>
			</body>
		</html>
	);
}
